"""Telegram Bot delivery — send tier articles + summary (FR29, QĐ6).

Handles: message formatting, smart splitting (4096 char limit),
tier labels, MarkdownV2 escaping, rate limiting delay.
"""

from __future__ import annotations

import asyncio
import html as html_lib
import os
import re
from dataclasses import dataclass
from typing import Any

import httpx

from cic_daily_report.core.error_handler import DeliveryError
from cic_daily_report.core.logger import get_logger
from cic_daily_report.core.retry_utils import retry_async

logger = get_logger("telegram_bot")

TG_MAX_LENGTH = 4000  # Telegram limit is 4096 but use 4000 for UTF-8 safety margin
SEND_DELAY = 1.5  # seconds between messages to avoid rate limiting

# Regex to match safe <a href="...">...</a> tags (no javascript:/data: URIs)
_SAFE_LINK_RE = re.compile(
    r'<a\s+href="(https?://[^"]+)">(.*?)</a>',
    re.IGNORECASE,
)

# Regex for safe HTML tags generated by md_to_tg_html() — preserve during escape
_SAFE_FORMAT_RE = re.compile(r"<(/?)([bi])>")


def md_to_tg_html(text: str) -> str:
    """Convert Markdown formatting to Telegram-safe HTML.

    Handles: ## headings → <b>, **bold** → <b>, *italic* → <i>,
    - bullets → •. Keeps content otherwise untouched.
    """
    lines = text.split("\n")
    result: list[str] = []
    for line in lines:
        stripped = line.strip()
        # ## Heading → <b>Heading</b>
        if stripped.startswith("## "):
            heading = stripped[3:].strip()
            result.append(f"<b>{heading}</b>")
            continue
        # - bullet or * bullet → • bullet
        if re.match(r"^[-*]\s+", stripped):
            bullet_text = re.sub(r"^[-*]\s+", "", stripped)
            stripped = f"• {bullet_text}"
        # **bold** → <b>bold</b> (non-greedy, avoid matching * italic *)
        stripped = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", stripped)
        # *italic* → <i>italic</i> (only single *, after ** already replaced)
        stripped = re.sub(r"(?<!\*)\*([^*]+?)\*(?!\*)", r"<i>\1</i>", stripped)
        result.append(stripped)
    return "\n".join(result)


def selective_html_escape(text: str) -> str:
    """Escape HTML but preserve safe tags (<a href>, <b>, <i>).

    Strategy: extract safe tags → escape everything → re-insert tags.
    Blocks javascript: and data: URIs to prevent XSS.
    """
    # Extract safe links and replace with placeholders
    safe_tags: list[str] = []

    def _replace_link(match: re.Match) -> str:
        safe_tags.append(match.group(0))
        return f"\x00TAG{len(safe_tags) - 1}\x00"

    def _replace_format(match: re.Match) -> str:
        safe_tags.append(match.group(0))
        return f"\x00TAG{len(safe_tags) - 1}\x00"

    text_with_placeholders = _SAFE_LINK_RE.sub(_replace_link, text)
    text_with_placeholders = _SAFE_FORMAT_RE.sub(_replace_format, text_with_placeholders)

    # Escape everything else
    escaped = html_lib.escape(text_with_placeholders)

    # Re-insert safe tags
    for i, tag in enumerate(safe_tags):
        escaped = escaped.replace(f"\x00TAG{i}\x00", tag)

    return escaped


@dataclass
class TelegramMessage:
    """A message ready to send via Telegram Bot API."""

    tier_label: str
    content: str
    part: int = 1
    total_parts: int = 1

    @property
    def formatted(self) -> str:
        """Full message text with tier label and part indicator."""
        if self.total_parts > 1:
            header = f"[{self.tier_label} - Phần {self.part}/{self.total_parts}]"
        else:
            header = f"[{self.tier_label}]"
        return f"{header}\n\n{self.content}"


def split_message(tier_label: str, content: str) -> list[TelegramMessage]:
    """Split content into TG-safe messages (QĐ6: split by section, not mid-sentence).

    Splits on section headers (## or **) when possible, falls back to newlines.
    """
    header_len = len(f"[{tier_label} - Phần 99/99]\n\n")
    max_content = TG_MAX_LENGTH - header_len

    if len(content) <= max_content:
        return [TelegramMessage(tier_label=tier_label, content=content)]

    # Split by sections (## headers or bold headers)
    sections = re.split(r"(?=\n##\s|\n\*\*[^*]+\*\*\n)", content)
    if len(sections) <= 1:
        # Fallback: split by double newlines
        sections = content.split("\n\n")

    parts: list[str] = []
    current = ""

    for section in sections:
        if len(current) + len(section) > max_content and current:
            parts.append(current.strip())
            current = section
        else:
            current += section

    if current.strip():
        parts.append(current.strip())

    # Hard fallback: if any part still exceeds max, chunk it
    final_parts: list[str] = []
    truncated = False
    for part in parts:
        while len(part) > max_content:
            truncated = True
            final_parts.append(part[:max_content])
            part = part[max_content:]
        if part.strip():
            final_parts.append(part.strip())
    parts = final_parts if final_parts else parts

    if truncated:
        logger.warning(f"Article [{tier_label}] truncated: content split into {len(parts)} parts")

    total = len(parts)
    return [
        TelegramMessage(tier_label=tier_label, content=p, part=i + 1, total_parts=total)
        for i, p in enumerate(parts)
    ]


def prepare_messages(
    articles: list[dict[str, str]],
) -> list[TelegramMessage]:
    """Prepare TelegramMessages from article dicts.

    Args:
        articles: list of {"tier": "L1", "content": "..."} or
                  {"tier": "Summary", "content": "..."}
    """
    messages: list[TelegramMessage] = []
    for article in articles:
        tier = article.get("tier", "")
        content = article.get("content", "")
        messages.extend(split_message(tier, content))
    return messages


class TelegramBot:
    """Telegram Bot API client for message delivery."""

    def __init__(
        self,
        bot_token: str | None = None,
        chat_id: str | None = None,
    ) -> None:
        self._token = bot_token or os.getenv("TELEGRAM_BOT_TOKEN", "")
        self._chat_id = chat_id or os.getenv("TELEGRAM_CHAT_ID", "")

        if not self._token or not self._chat_id:
            raise DeliveryError(
                "Telegram config missing — set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID",
                source="telegram_bot",
            )

    async def send_message(self, text: str, parse_mode: str = "HTML") -> dict[str, Any]:
        """Send a single message via Telegram Bot API with retry."""
        return await retry_async(
            self._send_raw,
            text=text,
            parse_mode=parse_mode,
        )

    async def _send_raw(self, text: str, parse_mode: str = "HTML") -> dict[str, Any]:
        """Raw send — called by retry wrapper.

        Uses selective HTML escape: preserves safe <a href> tags while escaping
        everything else to prevent Telegram parsing errors.
        """
        url = f"https://api.telegram.org/bot{self._token}/sendMessage"
        text = md_to_tg_html(text)
        text = selective_html_escape(text)
        payload = {
            "chat_id": self._chat_id,
            "text": text,
            "parse_mode": parse_mode,
        }

        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(url, json=payload)
            resp.raise_for_status()

        data = resp.json()
        if not data.get("ok"):
            raise DeliveryError(
                f"Telegram API error: {data.get('description', 'unknown')}",
                source="telegram_bot",
            )
        return data

    async def send_photo(
        self,
        photo_url: str,
        caption: str = "",
    ) -> dict[str, Any]:
        """Send a photo via Telegram Bot API sendPhoto.

        Args:
            photo_url: Public URL to the image.
            caption: Optional caption (max 1024 chars).
        """
        return await retry_async(self._send_photo_raw, photo_url, caption)

    async def _send_photo_raw(self, photo_url: str, caption: str = "") -> dict[str, Any]:
        """Raw sendPhoto — called by retry wrapper."""
        url = f"https://api.telegram.org/bot{self._token}/sendPhoto"
        payload: dict[str, Any] = {
            "chat_id": self._chat_id,
            "photo": photo_url,
        }
        if caption:
            payload["caption"] = selective_html_escape(caption)[:1024]
            payload["parse_mode"] = "HTML"

        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(url, json=payload)
            resp.raise_for_status()

        data = resp.json()
        if not data.get("ok"):
            raise DeliveryError(
                f"Telegram sendPhoto error: {data.get('description', 'unknown')}",
                source="telegram_bot",
            )
        return data

    async def deliver_all(
        self,
        messages: list[TelegramMessage],
    ) -> list[dict[str, Any]]:
        """Send all messages in order with delay between each (NFR18).

        Returns list of Telegram API responses.
        """
        results: list[dict[str, Any]] = []

        for i, msg in enumerate(messages):
            try:
                result = await self.send_message(msg.formatted)
                results.append(result)
                logger.info(f"Sent [{msg.tier_label}] part {msg.part}/{msg.total_parts}")

                # Delay between messages (except after last)
                if i < len(messages) - 1:
                    await asyncio.sleep(SEND_DELAY)

            except Exception as e:
                logger.error(f"Failed to send [{msg.tier_label}]: {e}")
                results.append({"ok": False, "error": str(e), "tier": msg.tier_label})

        sent = sum(1 for r in results if r.get("ok"))
        logger.info(f"Delivery complete: {sent}/{len(messages)} messages sent")
        return results
